[ADD] odoo 10 portage of base_phone_validation
OCA/connector-telephony pull request #146
Opened 2017-09-25 14:11 UTC by ventilooo

A v10 migration of #42

2017-10-02 15:13 UTC, leemannd approved these changes
Thanks. LGTM.
Only nitpicking. Could you update your pr to short headers?

2017-10-02 15:13 UTC, leemannd commented on base_phone_validation/__init__.py
> +#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
Short headers

2017-11-24 16:34 UTC, ventilooo commented
@leemannd ping ?

2017-11-24 16:39 UTC, rimbendhaou commented on base_phone_validation/models/res_partner.py
> +                    _(u'The number ({}) "{}" seems not valid for {}.').format(
@ventilooo In this error message you display the country name and in the other case (elif self.env.user.company_id.country_id:), the country code is displayed. Better to have the same message in all cases

2017-11-27 15:00 UTC, ventilooo commented on base_phone_validation/models/res_partner.py
> +                    _(u'The number ({}) "{}" seems not valid for {}.').format(
fixed

2018-02-27 18:12 UTC, foutoucour commented
Hello,

Do you think we could merge this pull request?

2018-02-27 18:58 UTC, ventilooo commented
@alexis-via 

It seems @foutoucour need that piece of code  :smile:

2018-03-06 14:13 UTC, foutoucour commented
Hey, it has been a week already ;(
Could anyone from OCA merge this approved PR? (@rimbendhaou @leemannd) Thank you

2018-03-07 14:11 UTC, leemannd commented
@foutoucour There is only one positive review (mine) you could try to add your review (functional/code review). It will help to have it merged.
By the way, I have no rights for merge

2018-05-30 18:15 UTC, rimbendhaou approved these changes
lgtm

2018-06-07 18:59 UTC, foutoucour approved these changes

2018-06-08 19:43 UTC, pedrobaeza requested changes

2018-06-08 19:43 UTC, pedrobaeza commented on base_phone_validation/i18n/base_phone_validation.pot
> +# Translation of Odoo Server.
Remove this file

2018-06-08 19:43 UTC, pedrobaeza commented on base_phone_validation/README.rst
> +Base Phone Validation
As the README misses some parts, you can take the occasion for using the new fragments system. Check OCA/maintainer-tools for the template

2018-06-08 19:43 UTC, pedrobaeza commented on base_phone_validation/models/res_partner.py
> +        for rec in self:
For avoiding one indentation level you can put

```
...self.filtered ('phone')
```

2018-06-08 19:43 UTC, pedrobaeza commented on base_phone_validation/models/res_partner.py
> +        for rec in self:
The same about filtered

2018-06-08 19:43 UTC, pedrobaeza commented on base_phone_validation/models/res_partner.py
> +    def _mobile_number_validation(self):
The same about filtered

2022-05-15 12:43 UTC, closed without merging