[ADD] 14.0_sms_no_automatic_delete
OCA/connector-telephony pull request #250
Opened 2021-06-21 07:02 UTC by Kev-Roche

Proposing a new module : sms_no_automatic_delete
It allows to save all sent sms and delete them after a specific delay.

2021-06-21 07:06 UTC, Kev-Roche commented
cc @alexis-via, @sebastienbeau

2021-06-21 07:15 UTC, sebastienbeau commented on sms_no_automatic_delete/models/sms_sms.py
> +
remove this empty line

2021-06-21 07:20 UTC, sebastienbeau requested changes

2021-06-21 07:20 UTC, sebastienbeau commented on sms_no_automatic_delete/models/sms_sms.py
> +        sms = self.env["sms.sms"].search([("write_date", "<=", purge_day)])
You can directly pass a datetime here so 

```suggestion
        sms = self.env["sms.sms"].search([("write_date", "<=", datetime.now() - timedelta(days=days))])
```

2021-06-21 07:20 UTC, sebastienbeau commented on sms_no_automatic_delete/tests/test_purge_and_unlink_sms.py
> +                "write_date": sms_30_days_ago,
Same here pass a datetime directly ;)

```suggestion
                "write_date": datetime.now() - timedelta(days=30),
```

2021-06-21 07:32 UTC, Kev-Roche commented on sms_no_automatic_delete/tests/test_purge_and_unlink_sms.py
> +                "write_date": sms_30_days_ago,
indeed, I did it in all files

2021-06-22 14:53 UTC, sebastienbeau approved these changes
LGTM code review

2021-06-24 14:40 UTC, Kev-Roche commented
cc @hparfr

2021-06-25 13:27 UTC, hparfr approved these changes

2021-07-02 14:09 UTC, sebastienbeau commented
/ocabot merge nobump

2021-07-02 14:18 UTC, merged