[IMP] new module to send SMS using Clickatell
OCA/connector-telephony pull request #252
Opened 2021-07-18 02:27 UTC by rpsjr

This is a new module to use odoo base SMS module to send SMS using Clickatell gateway.

2021-07-18 16:18 UTC, rvalyi requested changes

2021-07-18 16:18 UTC, rvalyi commented on .pre-commit-config.yaml0
> +  ^l10n_br_account/|
Hello @rpsjr , your module looks great however I think you are bringing some meta-files from the Brazilian localization that shouldn't be included in this PR. This is the case with this .pre-commit-config.yaml0, .isort.cfg, .coveragerc, .editorconfig0 files at least. Could you amend this PR (or better with rebase -i) to remove these files please?

2021-07-25 00:31 UTC, rpsjr commented
Please close this PR as it has ben remade at #255

2021-07-25 11:09 UTC, closed without merging

2021-07-25 11:11 UTC, rpsjr commented
PR as it has been remade at #255.