8.0 sms
OCA/connector-telephony pull request #55
Opened 2015-08-04 15:06 UTC by Viggor

Add modules to send sms to partner with ovh configuration.
Add a module to automatic sms sending when a deliver is ready.

The original sms module come from Julius.

2015-08-04 15:23 UTC, yvaucher commented
For contributor Hanane (no github login found) does he has a github account?

2015-08-04 15:25 UTC, Viggor commented
The module come from launchpad so he probably doesn't have a github account.

2015-08-04 15:28 UTC, yvanpatry commented
At my knowledge she don't have an github account and she no longer works with us so ! 

Cordialement, 
Yvan PATRY 

Julius Network Solutions 
32, rue du Général Foy 75008 Paris 
http://www.julius.fr/ 
Tel : +33 (0) 144 700 804 
Fax : +33 (0) 955 646 946 


De: "Viggor" <notifications@github.com> 
À: "OCA/connector-telephony" <connector-telephony@noreply.github.com> 
Cc: "yvan" <yvan@julius.fr> 
Envoyé: Mardi 4 Août 2015 17:25:53 
Objet: Re: [connector-telephony] 8.0 sms (#55) 



The module come from launchpad so he probably doesn't have a github account. 

— 
Reply to this email directly or view it on GitHub .

2015-08-04 15:28 UTC, yvaucher commented on .gitignore
> +*.pot
Don't add *.pot in gitignore

2015-08-04 15:30 UTC, yvaucher commented on sms_send_picking/__openerp__.py
> + 'description': """
Description should go in a README.rst file and you have to remove it completely from `__openerp__.py`

2015-08-04 15:31 UTC, yvaucher commented on sms_send_picking/__openerp__.py
> + 'category': 'Generic Modules',
Would `Phone` be better for category?

2015-08-04 15:31 UTC, yvaucher commented on sms_send_picking/__openerp__.py
> +
Please remove useless empty lines at end of file

2015-08-04 15:33 UTC, yvaucher commented on sms_send_picking/stock.py
> +        gateway = gateways[0]
You can do a `self.env[...].search(domain, limit=1)` to ensure you have only one gateway.

2015-08-04 15:40 UTC, yvaucher commented on sms_send_picking/stock.py
> +        default['sms_sent'] = False
Use `default` attribute when declaring the fields.Boolean instead.

2015-08-04 15:40 UTC, yvaucher commented on smsclient_core/__init__.py
> +# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
We agreed to remove vim lines noone stated that he was using it.

2015-08-04 15:41 UTC, yvaucher commented on sms_send_picking/__openerp__.py
> + 'author': 'Akretion',
Please add OCA in author

2015-08-04 15:41 UTC, yvaucher commented on smsclient_core/__openerp__.py
> +    "author": "Julius Network Solutions,SYLEAM,OpenERP SA,Akretion",
Please add OCA in author

2015-08-04 15:41 UTC, yvaucher commented on smsclient_core/__openerp__.py
> +    "description": """
description goes in README.rst

2015-08-04 15:42 UTC, yvaucher commented on smsclient_core/smsclient_wizard.xml
> +<?xml version="1.0" encoding="utf-8"?>
This file is not loaded. To remove?

2015-08-04 15:43 UTC, yvaucher commented on smsclient_core/smsclient.py.backup
> +# -*- coding: utf-8 -*-
To cleanup

2015-08-04 15:43 UTC, yvaucher commented on smsclient_core/serveraction_view.xml
> +                <!-- <field name="sms" position="attributes"> -->
Remove those commented lines

2015-08-04 15:45 UTC, yvaucher commented on smsclient_core/serveraction.py
> +    mobile = fields.Char('Mobile No', size=512, help="Provides fields that "
You can remove size or is it intended to limit to 512 ?

2015-08-04 15:49 UTC, yvaucher commented on smsclient_core/serveraction.py
> +                    print sms_in_q
Is this intended for debugging? If so use logging. Or remove it.

2015-08-04 15:51 UTC, yvaucher commented on smsclient_core/smsclient.py
> +    password = fields.Char('Password', size=256)
Size is not mandatory anymore. Any reason to define it?

2015-08-04 15:52 UTC, yvaucher commented on smsclient_core/smsclient.py
> +                      required=True, help='Base url for message')
size constraint to remove.

2015-08-04 15:53 UTC, yvaucher commented on smsclient_core/smsclient.py
> +                              select=True,
Please use `index` instead of `select`

2015-08-04 15:53 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        ], 'Gateway Status', select=True, readonly=True, default='new')
s/select/index

2015-08-04 15:54 UTC, yvaucher commented on smsclient_core/smsclient.py
> +                       help="The message text that will be send along with the"
Warning your help message will concat "... along with theemail which ..."

2015-08-04 15:55 UTC, yvaucher commented on smsclient_core/smsclient.py
> +                              help='The maximum time - in minute(s) -'
Add a space before last `'`

2015-08-04 15:56 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        ('3', '3')
I see this list multiple times. If it is the same values it could be a constant.

2015-08-04 15:57 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        ('3', 'Toolkit')
Same here, put this selection in a constant

2015-08-04 15:57 UTC, yvaucher commented on smsclient_core/smsclient.py
> +    tag = fields.Char('Tag', size=256, help='an optional tag')
Any reason for the `size` ?

2015-08-04 16:00 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        if self.method == '':
`if not self.method` ?

2015-08-04 16:04 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        self.env.cr.commit()
You should certainly remove this commit and return the result of super. Or is there any reason to do it this way? If so a comment would be very appreciated but I think this is strange.

2015-08-04 16:05 UTC, yvaucher commented on smsclient_core/smsclient_view.xml
> +						</page>
Please fix the indentation of this file there are a bunch of tab we only want spaces

2015-08-04 16:07 UTC, yvaucher commented on smsclient_core/smsclient_view.xml
> +                </tree>
Maybe you want an editable view list here as form gives no advantages.

2015-08-04 16:09 UTC, yvaucher commented on smsclient_core/__openerp__.py
> +    "description": """
And please provide credits for  smsclient_core/static/src/img/icon.png in README.rst

Here is a template to follow: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2015-08-04 16:10 UTC, yvaucher commented on smsclient_core/__openerp__.py
> +Sending SMSs very easily, individually or collectively.
This first line can definitively goes into `summary` of `__openerp__.py`

2015-08-04 16:10 UTC, yvaucher commented on smsclient_core/__openerp__.py
> +    "category": "Tools",
Phone ?

2015-08-04 16:11 UTC, yvaucher commented on smsclient_core/partner_sms_send_view.xml
> +              <form string="SMS - Gateway: clickatell" version="7.0">
To remove `version="7.0"`

2015-08-04 16:12 UTC, yvaucher commented on smsclient_core/partner_sms_send_view.xml
> +							<field name="user" invisible="1"/>
Please fix that messy indentation

2015-08-04 16:14 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        if i > 1:
Would be simple to check if len(active_ids) > 1

2015-08-04 16:14 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        gateway_ids = sms_obj.search([], limit=1)
Please rename this variable you don't get ids but a single record set

2015-08-04 16:15 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        return gateway_ids and gateway_ids[0] or False
gateway_ids[0] == gateway_ids

2015-08-04 16:16 UTC, yvaucher commented on smsclient_core/smsclient.py
> +    def onchange_gateway(self, gateway_id):
You might want to change this to new api to remove it from xml.

2015-08-04 16:17 UTC, yvaucher commented on smsclient_core/smsclient.py
> +        help='The time -in minute(s)- to wait before sending the message',
s/time -in minute(s)/time - in minute(s)/

2015-08-04 16:19 UTC, yvaucher commented on smsclient_ovh/__openerp__.py
> +    "description": """
Another description to put in a README.rst

2015-08-04 16:19 UTC, yvaucher commented on smsclient_ovh/__openerp__.py
> +    "author": "Julius Network Solutions,SYLEAM,OpenERP SAi,Akretion",
Missing OCA and type on OpenERP SA

2015-08-04 16:25 UTC, yvaucher commented
Thanks for the porting on github of those modules.
You have my inline comments as a code review.

Plus have a look at travis: https://travis-ci.org/OCA/connector-telephony/jobs/74086845

2015-08-04 16:35 UTC, Viggor commented
@yvaucher Thank you for this big review! I've fixed most of your comments.

2015-08-05 14:05 UTC, Viggor commented
Author name correctly added and space added for proper concat. Thanks for all!

2015-08-05 14:51 UTC, yvaucher commented
@Viggor You might have missed a comment on smsclient_core/smsclient.py on priority field

2015-08-05 17:16 UTC, Viggor commented
The travis errors come from the module base_phone, so everything is ok on my side.

2015-09-15 20:18 UTC, sebastienbeau commented on smsclient_core/smsclient.py
> +class Properties(models.Model):
It seem that this class is no longer used. Remove it if it's dead code

2015-09-15 20:20 UTC, sebastienbeau commented on smsclient_core/smsclient.py
> +class HistoryLine(models.Model):
No sure that an HistoryLine object is needed. We can just keep the mail send in the queue with the state send for the history, what do you think?

2015-09-15 20:22 UTC, sebastienbeau commented on smsclient_core/wizard/sendcode.py
> +#    states = {
if it's dead code, remove it

2015-09-15 20:23 UTC, sebastienbeau commented on smsclient_core/wizard/verifycode.py
> +    states = {
I think this code come from V5, not needed anymore on 8

2015-09-15 20:25 UTC, sebastienbeau commented on smsclient_core/smsclient.py
> +
Add teh company id so we can only see the sms of our company

2015-09-23 08:46 UTC, legalsylvain commented on .gitignore
> +downloads/
please remove changes in gitignore.

2015-09-23 09:02 UTC, legalsylvain commented on smsclient_ovh/sms_gateway.py
> +                      self.gateway_id.url, params)
I know that this is a debug logger but is it great to have password gateway in log ?

2015-09-23 12:58 UTC, sebastienbeau commented on smsclient_ovh/sms_gateway.py
> +                      self.gateway_id.url, params)
Good catch ! thanks !

2017-03-21 14:17 UTC, yvaucher requested changes

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/README.rst
> +===========
Please update this README according to last version:

https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

Title must have enough `=`

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/README.rst
> +`here <https://github.com/OCA/{project_repo}/issues/new?body=module:%20{module_name}%0Aversion:%20{version}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20beh
Update this part by removing this link

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/OCA/{project_repo}/issues>`_.
replace `{project_repo}` place holder

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/README.rst
> +* https://www.odoo.com/forum/help-1
Remove this link and add the Try me on runbot button

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/stock.py
> +###############################################################################
Use short header

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/__openerp__.py
> +# © 2015 Valentin CHEMIERE <valentin.chemiere@akretion.com>
Prefer Copyright instead of `©`

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/stock.py
> +    @api.model
In this method you are using `self.partner_id` and `self.company_id` thus it should be `api.multi`

2017-03-21 14:17 UTC, yvaucher commented on sms_send_picking/stock.py
> +            picking.write({'availability_sent_by_sms': True})
As you write a single field you can do:

``` python
picking.availability_sent_by_sms = True
```

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/README.rst
> +`here <https://github.com/OCA/{project_repo}/issues/new?body=module:%20{module_name}%0Aversion:%20{version}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20beh
Update this file according to https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/OCA/{project_repo}/issues>`_.
Replace `{project_repo}`

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/README.rst
> +
Add "Try me on runbot" button

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/__init__.py
> +##############################################################################
You can remove the license header from `__init__.py` file or you must use the small license header:
https://github.com/OCA/maintainer-tools/blob/master/template/module/models/model_name.py#L1-L3

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/__openerp__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Update this to the last version of the small license header:

https://github.com/OCA/maintainer-tools/blob/master/template/module/models/model_name.py#L1-L3

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/serveraction.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
https://github.com/OCA/maintainer-tools/blob/master/template/module/models/model_name.py#L1-L3

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/serveraction.py
> +    sms = fields.Char('SMS', size=160, translate=True)
Don't we need a constraint on size ? 160 char is for 7-bit characters (ASCII). You won't be prevented to enter non ASCII characters here.

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/sms_gateway.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
https://github.com/OCA/maintainer-tools/blob/master/template/module/models/model_name.py#L1-L3

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/sms_gateway.py
> +            if sms.gateway_id.char_limit and len(sms.message) > 160:
This doesn't handle if `coding` is unicode plus message is very likely to include non-ascii characters.

It would be a good idea to make a function for this check as you might want to use it at different places.

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/sms_gateway_view.xml
> +                        <group col="2">
What you probably want here is a

``` xml
<div class="oe_title">
    <h1><field name="name"/></h1>
    <field name="Method" placeholder="Method"/>
</div>
```

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/sms_gateway_view.xml
> +                        <label for="partner_id" class="oe_edit_only"/>
Put this in a `<div class="oe_title">`

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/sms_gateway_view.xml
> +                <tree string="Sms">
What about adding `colors="red:state == 'error'; blue: state == 'draft'; grey: state == 'send'"`

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/smstemplate.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
https://github.com/OCA/maintainer-tools/blob/master/template/module/models/model_name.py#L1-L3

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/smstemplate_view.xml
> +				</field>
Please don't mix tab and spaces

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/wizard/__init__.py
> +##############################################################################
No header or short header

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/wizard/mass_sms.py
> +##############################################################################
Short header

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/wizard/mass_sms.py
> +    @api.model
`@api.multi`

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/wizard/mass_sms_view.xml
> +            	<form string="SMS Gateway - Sens SMS" version="7.0">
Remove `version="7.0"`

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/wizard/mass_sms_view.xml
> +					<notebook>
Don't mix tab and spaces

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/wizard/mass_sms_view.xml
> +                                <tree options="{'limit': 10}">
My wild guess is that `options` is not working, please remove it.

2017-03-21 14:17 UTC, yvaucher commented on smsclient_core/wizard/mass_sms_view.xml
> +	                   	<page string="Additional option">
s/option/options

2017-03-21 14:17 UTC, yvaucher commented on smsclient_ovh/README.rst
> +`here <https://github.com/OCA/{project_repo}/issues/new?body=module:%20{module_name}%0Aversion:%20{version}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20beh
Readme file to update

2017-03-21 14:17 UTC, yvaucher commented on smsclient_ovh/__init__.py
> +##############################################################################
No header or short header

2017-03-21 14:17 UTC, yvaucher commented on smsclient_ovh/__openerp__.py
> +##############################################################################
Short header

2017-03-21 14:17 UTC, yvaucher commented on smsclient_ovh/__openerp__.py
> +# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
You can remove the vim line

2017-03-21 14:17 UTC, yvaucher commented on smsclient_ovh/sms_gateway.py
> +###############################################################################
Short header

2017-03-21 14:17 UTC, yvaucher commented on smsclient_ovh/__openerp__.py
> +    "version": "1.0",
`8.0.1.0.0`

2017-03-21 14:17 UTC, yvaucher commented on smsclient_ovh/sms_gateway.py
> +    @api.model
`@api.multi`

2022-01-02 12:33 UTC, closed without merging